#!/bin/sh

echo 'ai_use_torch_dynamic_lights on
bemsg 1
unbindall
cam_inert 0.
cam_slide_inert 0.25
cl_cod_pickup_mode 1
cl_dynamiccrosshair on
con_sensitive 0.15
g_always_run on
g_autopickup on
g_backrun on
g_corpsenum 10
g_dynamic_music on
g_eventdelay 0
g_game_difficulty gd_novice
hud_crosshair on
hud_crosshair_dist off
hud_info on
hud_weapon on
mm_mm_net_srv_dedicated off
mm_net_con_publicserver off
mm_net_con_spectator 20
mm_net_con_spectator_on off
mm_net_filter_battleye on
mm_net_filter_empty on
mm_net_filter_full off
mm_net_filter_listen on
mm_net_filter_pass on
mm_net_filter_wo_ff on
mm_net_filter_wo_pass on
mm_net_srv_gamemode st_deathmatch
mm_net_srv_maxplayers 32
mm_net_srv_name Stalker
mm_net_srv_reinforcement_type 0
mm_net_use_battleye off
mm_net_weather_rateofchange 1.
mouse_invert off
mouse_sens 0.12
net_cl_icurvesize 0
net_cl_icurvetype 0
net_cl_interpolation 0.
net_cl_log_data off
net_compressor_enabled 0
net_compressor_gather_stats 0
net_dbg_dump_export_obj 0
net_dbg_dump_import_obj 0
net_dbg_dump_update_read 0
net_dbg_dump_update_write 0
net_dedicated_sleep 5
net_sv_gpmode 0
net_sv_log_data off
net_sv_pending_lim 3
net_sv_update_rate 30
ph_frequency 100.00000
ph_iterations 18
r1_dlights on
r1_dlights_clip 50.
r1_fog_luminance 1.
r1_glows_per_frame 16
r1_lmodel_lerp 0.1
r1_no_detail_textures off
r1_pps_u 0.
r1_pps_v 0.
r1_ssa_lod_a 64.
r1_ssa_lod_b 48.
r1_tf_mipbias 0.
r2_aa off
r2_aa_break 0.000000,1.000000,1.000000
r2_aa_kernel 0.5
r2_aa_weight 0.250000,0.250000,0.000000
r2_allow_r1_lights off
r2_detail_bump on
r2_dof -1.250000,1.400000,300.000000
r2_dof_enable on
r2_dof_kernel 5.
r2_dof_sky 30.
r2_exp_donttest_shad off
r2_gi off
r2_gi_clip 0.001
r2_gi_depth 1
r2_gi_photons 16
r2_gi_refl 0.9
r2_gloss_factor 4.
r2_ls_bloom_fast off
r2_ls_bloom_kernel_b 0.7
r2_ls_bloom_kernel_g 3.
r2_ls_bloom_kernel_scale 0.8
r2_ls_bloom_speed 100.
r2_ls_bloom_threshold 0.2
r2_ls_depth_bias -0.0003
r2_ls_depth_scale 1.00001
r2_ls_dsm_kernel 0.7
r2_ls_psm_kernel 0.7
r2_ls_squality 1.
r2_ls_ssm_kernel 0.7
r2_mblur 0.
r2_parallax_h 0.02
r2_slight_fade 0.5
r2_soft_particles on
r2_soft_water on
r2_ssa_lod_a 64.
r2_ssa_lod_b 48.
r2_ssao st_opt_high
r2_ssao_blur off
r2_steep_parallax on
r2_sun on
r2_sun_depth_far_bias -0.00002
r2_sun_depth_far_scale 1.
r2_sun_depth_near_bias 0.00001
r2_sun_depth_near_scale 1.
r2_sun_details off
r2_sun_far 100.
r2_sun_focus on
r2_sun_lumscale 1.
r2_sun_lumscale_amb 1.
r2_sun_lumscale_hemi 1.
r2_sun_near 16.
r2_sun_near_border 0.75
r2_sun_quality st_opt_ultra
r2_sun_shafts st_opt_high
r2_sun_tsm on
r2_sun_tsm_bias -0.01
r2_sun_tsm_proj 0.3
r2_tf_mipbias 0.
r2_tonemap on
r2_tonemap_adaptation 1.
r2_tonemap_amount 0.7
r2_tonemap_lowlum 0.0001
r2_tonemap_middlegray 1.
r2_volumetric_lights on
r2_wait_sleep 0
r2_zfill off
r2_zfill_depth 0.5
r2em 2.2
r3_dynamic_wet_surfaces on
r3_dynamic_wet_surfaces_far 30.
r3_dynamic_wet_surfaces_near 10.
r3_dynamic_wet_surfaces_sm_res 256
r3_gbuffer_opt on
r3_minmax_sm autodetect
r3_volumetric_smoke off
r__detail_density 0.2
r__dtex_range 50.
r__geometry_lod 1.
r__supersample 1
r__tf_aniso 16
r__wallmark_ttl 60.
rs_c_brightness 1.
rs_c_contrast 1.
rs_c_gamma 1.
rs_cam_pos off
rs_constant_fps off
rs_fullscreen off
rs_refresh_60hz on
rs_skeleton_update 32
rs_stats off
rs_v_sync off
rs_vis_distance 1.
snd_acceleration on
snd_cache_size 32
snd_device Generic Software
snd_efx on
snd_targets 32
snd_volume_eff 1.
snd_volume_music 1.
sv_activated_return 0
sv_anomalies_enabled 1
sv_anomalies_length 3
sv_artefact_respawn_delta 30
sv_artefact_returning_time 45
sv_artefact_spawn_force 0
sv_artefact_stay_time 3
sv_artefacts_count 10
sv_auto_team_balance 0
sv_auto_team_swap 1
sv_bearercantsprint 1
sv_client_reconnect_time 60
sv_console_update_rate 1
sv_dedicated_server_update_rate 100
sv_dmgblockindicator 1
sv_dmgblocktime 0
sv_dump_online_statistics_period 0
sv_forcerespawn 0
sv_fraglimit 10
sv_friendly_indicators 0
sv_friendly_names 0
sv_friendlyfire 1.
sv_hail_to_winner_time 7
sv_invincible_time 5
sv_max_ping_limit 2000
sv_pda_hunt 1
sv_reinforcement_time 0
sv_remove_corpse 1
sv_remove_weapon 1
sv_returnplayers 1
sv_rpoint_freeze_time 0
sv_shieldedbases 1
sv_show_player_scores_time 3
sv_spectr_firsteye 1
sv_spectr_freefly 0
sv_spectr_freelook 1
sv_spectr_lookat 1
sv_spectr_teamcamera 1
sv_statistic_collect 1
sv_teamkill_limit 3
sv_teamkill_punish 1
sv_timelimit 0
sv_vote_enabled 255
sv_vote_participants 0
sv_vote_quota 0.51
sv_vote_time 1.
sv_warm_up 0
texture_lod 0
wpn_aim_toggle 0

ph_iterations 18
r1_dlights_clip 30
r1_glows_per_frame 16
r2_detail_bump on
r2_dof_enable on
r2_ls_squality 1
r2_slight_fade 0.5
r2_soft_particles on
r2_soft_water on
r2_ssao st_opt_low
r2_steep_parallax on
r2_sun_quality st_opt_medium
r2_sun_shafts st_opt_low
r2_volumetric_lights on
r3_dynamic_wet_surfaces on
r3_volumetric_smoke off
r__detail_density 0.4
r__geometry_lod 0.5
r__supersample 1
r__tf_aniso 4
r__wallmark_ttl 40
rs_skeleton_update 32
rs_vis_distance 1
snd_cache_size 32
snd_targets 32
texture_lod 1

renderer renderer_r2
vid_mode 1280x720
r3_msaa st_opt_off
r3_msaa_alphatest st_opt_off
r3_use_dx10_1 off' > test.ltx

OSNAME=$(uname -s)

if [ "$OSNAME" = "Linux" ]; then
    #in case cp is alias to cp -i
    /bin/cp -rf test.ltx "$WINEPREFIX/drive_c/users/Public/Documents/ClearSkyBench/_appdata_/test.ltx"
else
    /bin/cp -rf test.ltx "C:/Users/Public/Documents/ClearSkyBench/_appdata_/test.ltx"
fi
