#!/bin/sh
echo '-- [Game-Configuration]
-- Attention: This file is re-generated by the system! Editing is not recommended! 

cl_bob = 1
cl_invertController = 0
cl_invertMouse = 0
cl_sensitivity = 45
cl_voice_volume = 1
dt_enable = 0
g_blood = 0
g_buddyMessagesIngame = 1
g_displayIgnoreList = 1
g_enableAlternateIronSight = 0
g_PSTutorial_Enabled = 1
g_quickGame_map = ""
g_quickGame_min_players = 1
g_quickGame_mode = "InstantAction"
g_quickGame_prefer_favorites = 1
g_quickGame_prefer_lan = 1
g_quickGame_prefer_mycountry = 1
g_startFirstTime = 0
hud_crosshair = 6
hud_showAllObjectives = 0
hud_subtitles = 0
i_forcefeedback = 1
i_mouse_smooth = 0
net_enable_voice_chat = 1
r_Brightness = 0.5
r_Contrast = 0.5
r_Fullscreen = 0
r_Gamma = 1
r_Height = 720
r_Width = 1280
s_DialogVolume = 1
s_MusicVolume = 0.6
s_SFXVolume = 1
sys_spec_GameEffects = 1
sys_spec_ObjectDetail = 3
sys_spec_Particles = 1
sys_spec_Physics = 2
sys_spec_PostProcessing = 1
sys_spec_Shading = 3
sys_spec_Shadows = 2
sys_spec_Sound = 1
sys_spec_Texture = 3
sys_spec_VolumetricEffects = 1
sys_spec_Water = 2
' > game.cfg

OSNAME=$(uname -s)

if [ "$OSNAME" = "Linux" ]; then
    mkdir -p "$WINEPREFIX/drive_c/users/$USER/My Documents/My Games/CRYSIS_SP_DEMO"
    cp game.cfg "$WINEPREFIX/drive_c/users/$USER/My Documents/My Games/CRYSIS_SP_DEMO/game.cfg"
else
    mkdir -p "C:/Users/$USERNAME/My Documents/My Games/CRYSIS_SP_DEMO"
    cp game.cfg "C:/Users/$USERNAME/My Documents/My Games/CRYSIS_SP_DEMO/game.cfg"
fi
